- .github/workflows/checks.yaml
Run checks upon push to main and daily on default branch.
* Risk: low
> [Changed] Run checks upon push to main and daily on default branch.

- ts/backend/src/app/features/server/router.mts
- ts/backend/src/app/features/services/sql-service.mts
- ts/common/api-endpoints.mts
- ts/common/api-types.mts
- ts/common/interfaces.mts
- ts/frontend/src/app/features/api/api.service.ts
- ts/frontend/src/app/views/benchmarks-detail/benchmarks-detail.view.html
- ts/frontend/src/app/views/benchmarks-detail/benchmarks-detail.view.ts
The user (submitter) now has to opt-in into publishing the source code explicitly i.o.t. publish the result.
Closes #31 
* Risk: low
* Discussion: mid - is there an EULA document available?
> [Changed] Publish result when eula accepted

- ts/frontend/src/app/views/home/home.view.html
- ts/frontend/tailwind.config.js
Changed theme to the one used on flatland.cloud
Closes #103 
* Risk: low
> [Changed] Use same theme as flatland.cloud

- docs/DEVELOPMENT.md
- ts/backend/src/app/features/server/router.mts
- ts/common/api-endpoints.mts
- ts/common/interfaces.mts
- ts/frontend/src/app/components/benchmark-card/benchmark-card.component.ts
- ts/frontend/src/app/components/leaderboard/leaderboard.component.html
- ts/frontend/src/app/components/leaderboard/leaderboard.component.ts
- ts/frontend/src/app/views/benchmarks-detail/benchmarks-detail.view.html
- ts/frontend/src/app/views/benchmarks-detail/benchmarks-detail.view.ts
- ts/frontend/src/app/views/participate/participate.view.ts
Benchmark-detail now shows a public leaderboard (that is, the 3 best results that are public).
Closes #30
* Risk: low
* Discussion: mid - I'm missing the knowledge how to aggregate separate scenario rewards into a single test score, hence there's no per-test-score display currently. Maybe we can tackle this later?
> [Added] Public leaderboard

- evaluation/compute_worker/tasks.py
Make supported client versions of evaluator configurable in compute worker
Closes #75 
* Risk: low
> [Added] #75 Make supported client versions configurable.

- evaluation/docker-compose-demo.yml
Reduce Rabbit healthcheck interval.
* Risk: low
> [Changed] Reduce Rabbit healthcheck interval.

- .github/pull_request_template.md
Cleanup pr template.
* Risk: low
> [Changed] Cleanup pr template.

- evaluation/compute_worker/tasks.py
- evaluation/compute_worker/tasks_docker_compose.py
- evaluation/pytest.ini
- evaluation/test_containers.py
Evaluate only selected tests in docker compose task implementation
Closes #78
* Risk: mid
> [Added] #78 Evaluate only selected tests

- ts/backend/src/app/features/server/router.mts
- ts/common/api-endpoints.mts
- ts/frontend/src/app/app.component.ts
- ts/frontend/src/app/app.routes.ts
- ts/frontend/src/app/components/benchmark-card/benchmark-card.component.html
- ts/frontend/src/app/components/leaderboard/leaderboard.component.html
- ts/frontend/src/app/components/leaderboard/leaderboard.component.ts
- ts/frontend/src/app/features/auth/auth.service.ts
- ts/frontend/src/app/views/benchmarks-detail/benchmarks-detail.view.html
- ts/frontend/src/app/views/benchmarks/benchmarks.view.html
- ts/frontend/src/app/views/benchmarks/benchmarks.view.ts
- ts/frontend/src/app/views/home/home.view.html
- ts/frontend/src/app/views/new-submission/new-submission.view.html
- ts/frontend/src/app/views/new-submission/new-submission.view.ts
- ts/frontend/src/app/views/participate/participate.view.html
- ts/frontend/src/app/views/participate/participate.view.ts
- ts/frontend/src/app/views/submission/submission.view.html
- ts/frontend/src/app/views/submission/submission.view.ts
- ts/frontend/src/index.html
- ts/frontend/tailwind.config.js
* Public area is now strictly separated from user area: select benchmark first, then chose to participate.
* Participate view lists own submissions.
* Submission form is on separate view.
Closes #105 
* Risk: low
* Discussion: mid - is flow UX good enough?
> [Changed] #105 Submission flow

- docs/ARCHITECTURE.md
- evaluation/compute_worker/tasks.py
- evaluation/compute_worker/tasks_docker_compose.py
- evaluation/compute_worker/test_tasks.py
- evaluation/test_containers.py
Fail fast if either submission or evaluation fails.
#99 
* Risk: low
> [Added] #99 Fail fast if either submission or evaluation fails.

- ts/backend/src/app/features/server/router.mts
- ts/frontend/src/app/app.component.ts
- ts/frontend/src/app/features/api/api.service.ts
Internal (i.e. requiring a logged in user) endpoints now check for presence of valid token. Also: removed debug output.
Closes #108 
Closes #88 
* Risk: low
> [Security] Backend auth guard

- evaluation/evaluator/Dockerfile
Follow https://docs.docker.com/go/dockerfile/rule/json-args-recommended/
Closes #86
* Risk: 
* Discussion:
> [Changed] #86 Follow JSON arguments recommended.

- .github/workflows/release-please.yml
inline image build jobs instead of triggering workflows from release-please workflow.
#41 
* Risk: 
* Discussion:
> ci: inline image build jobs instead of triggering workflows from release-please workflow.

- .github/workflows/release-please.yml
> ci: fix typo int image tag.

- .gitignore
- evaluation/.env.volumes.template
Update volumes dotenv template (KEYCLOAK was missing).
Renamed the template file to `.env.volumes.template`, explicitly un-.gitignore it, following this [this advice on StackOverflow](https://stackoverflow.com/a/78463831/10135201)
No issue.
* Risk: low
> chore: Update .env.volume.template

- package-lock.json
Audited and updated npm packages
https://github.com/flatland-association/flatland-benchmarks/security/dependabot/13
https://github.com/flatland-association/flatland-benchmarks/security/dependabot/12
* Risk: low
> chore: npm audit 2025-05-09

- .github/workflows/checks.yml
- ts/backend/src/app/features/controller/results.controller.mts
* Add swagger validation to gh action using openapi-generator-cli.
* Fix swagger-docs
Closes #228 
* Risk:  low
* Discussion:  low
> ci: Add swagger validation to gh action using openapi-generator-cli.

- .github/workflows/checks.yml
- ts/backend/src/app/features/controller/debug.controller.mts
- ts/backend/src/app/features/controller/health.controller.mts
- ts/backend/src/app/features/controller/submission.controller.mts
- ts/backend/src/app/features/services/celery-client-service.mts
- ts/backend/src/app/features/services/sql-service.spec.ts
- ts/backend/src/app/main.mts
- ts/backend/test/controller.test-adapter.mts
- ts/backend/test/integration/celery-client-service.spec.ts
- ts/backend/test/integration/health.controller.spec.ts
- ts/backend/test/integration/setup.mts
* Fix linting
* Run linter in ci.
Fixes #249 
* Risk:  low
* Discussion:  low
> ci: run eslint in ci.

- deployment/backend/start.sh
- evaluation/docker-compose-base.yml
- evaluation/evaluator/Dockerfile
- evaluation/orchestrator/evaluator_job.yaml
- evaluation/orchestrator/submission_job.yaml
- evaluation/rabbitmq/init.sh
Add `set -euxo pipefail` in all entrypoints/shell scripts.
Close #226 
* Risk: 
* Discussion:
> build: use set -euxo pipefail in all entrypoints.

- ts/backend/package.json
- ts/backend/src/app/features/controller/results.controller.mts
> build: fail swagger jsdoc

- package.json
- ts/backend/src/app/features/controller/results.controller.mts
- ts/backend/src/app/features/utils/aggregator.mts
- ts/backend/src/migration/data/V4.1__ai4realnet_example.sql
- ts/backend/src/migration/schema/V4__add_test_loop.sql
- ts/backend/test/integration/benchmark.controller.spec.ts
- Add example data
- Add `loop` descriptor to test definition
Closes #277 
Closes #278 
* Risk: low
> feat: Add AI4REALNET example

- deployment/backend/Dockerfile
- deployment/backend/start.sh
* Add `public.airealnet` and `public.fab` folder into docker image. 
* Add possibility to define `CUSTOMIZATION` env var to copy the files to the required folder in entrypoint
#270 
* Risk: 
* Discussion:
> 270 add public to docker image

- .github/workflows/release-please.yml
inject `FAB_VERSION` into backend image
Post-fixes #298
* Risk:  low
* Discussion:  low
> build: fix FAB_VERSION injection backend image.

- deployment/backend/start.sh
> ops: allow args in entrypoint for fab backend.

- deployment/backend/Dockerfile
> build: fix version injection.

- .github/workflows/release-please.yml
> Fix version injection

- evaluation/flatland3_benchmarks/gen_flatland3_benchmarks_sql.py
Generate data for AI4REALNET-int.flatland.cloud.
* Risk: 
* Discussion:
> ops: gen playground data for connection tests ai4realnet-int.

- docker/flatland3_benchmarks/orchestrator/orchestrator_docker_compose.py
- evaluation/flatland3_benchmarks/README.md
- evaluation/flatland3_benchmarks/evaluator/environment.yml
- evaluation/flatland3_benchmarks/evaluator/test_containers_flatland_benchmarks.py
- evaluation/flatland3_benchmarks/orchestrator/orchestrator.py
- evaluation/flatland3_benchmarks/orchestrator/orchestrator_common.py
* feature: use SUPPORTED_CLIENT_VERSION_RANGE for flatland3_benchmarks instead of SUPPORTED_CLIENT_VERSIONS.
https://github.com/flatland-association/flatland-rl/pull/261
* Risk:  mid
* Discussion:  low
> feature: use SUPPORTED_CLIENT_VERSION_RANGE.

- README.md
* docs: gathering nomenclature.
#402
* Risk:  mid
* Discussion:  mid
> docs: gathering nomenclature.

- ts/frontend/src/app/app.component.html
- ts/frontend/src/app/app.component.ts
- ts/frontend/src/app/app.routes.ts
- ts/frontend/src/app/components/breadcrumbs/breadcrumbs.component.html
- ts/frontend/src/app/components/breadcrumbs/breadcrumbs.component.ts
* Add breadcrumbs name resolver
Touches #287 - not closing yet. To reduce work, it makes IMHO sense to tackle #323 and #382 and finish #287 in one go
* Risk: low
> feat(frontend): Prettify breadcrumbs

- ts/frontend/src/app/views/benchmark-group/benchmark-group.view.html
- ts/frontend/src/app/views/benchmark/benchmark.view.html
- ts/frontend/src/app/views/submission/submission.view.html
- ts/frontend/src/app/views/test/test.view.html
- Render description fields as html (sanitized, i.e. tags considered harmful are stripped)
Closes #388 
* Risk: low
> feat(frontend): Render descriptions as html

- definitions/ai4realnet/gen_ai4realnet_benchmarks_sql.py
> fix: gen ai4realnet benchmarks SQL.

- .github/workflows/checks.yml
- evaluation/flatland3_benchmarks/orchestrator/requirements.txt
Depends on https://github.com/flatland-association/ai4realnet-orchestrators/pull/11 to be merged.
* Risk: 
* Discussion:
> refactor: Revert dependency main.

- .github/workflows/checks.yml
> chore: update dependencies.

- ts/backend/src/app/features/services/aggregator-service.spec.ts
- ts/backend/src/app/features/services/celery-client-service.mts
- ts/backend/test/integration/aggregator-service.spec.ts
- ts/backend/test/integration/benchmark.controller.spec.ts
- ts/backend/test/integration/celery-client-service.spec.ts
- ts/backend/test/integration/field.controller.spec.ts
- ts/backend/test/integration/health.controller.spec.ts
- ts/backend/test/integration/info.controller.spec.ts
- ts/backend/test/integration/results.controller.spec.ts
- ts/backend/test/integration/scenario.controller.spec.ts
- ts/backend/test/integration/setup.mts
- ts/backend/test/integration/sql-service.spec.ts
- ts/backend/test/integration/submission.controller.spec.ts
- ts/backend/test/integration/test.controller.spec.ts
- Configure logger per spec file.
- Use logger in celery-client-service
Closes #358 
* Risk: low
> test(backend): Fix logger output in tests
